spring:
  datasource:
      url: jdbc:mysql://localhost:3306/krasnopolskyi_db?createDatabaseIfNotExist=true
      username: root
      password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
token:
  signing:
    key: S3Jhc25vcG9sc2t5aU1ha3N5bVZpYWNoZXNsYXZvdmljaA==